// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package enums

import (
	"database/sql/driver"
	"fmt"
)

// Enum values for CommitOperation
const (
	CommitOperationCreate CommitOperation = "create"
	CommitOperationUpdate CommitOperation = "update"
	CommitOperationDelete CommitOperation = "delete"
)

func AllCommitOperation() []CommitOperation {
	return []CommitOperation{
		CommitOperationCreate,
		CommitOperationUpdate,
		CommitOperationDelete,
	}
}

type CommitOperation string

func (e CommitOperation) String() string {
	return string(e)
}

func (e CommitOperation) Valid() bool {
	switch e {
	case CommitOperationCreate,
		CommitOperationUpdate,
		CommitOperationDelete:
		return true
	default:
		return false
	}
}

// useful when testing in other packages
func (e CommitOperation) All() []CommitOperation {
	return AllCommitOperation()
}

func (e CommitOperation) MarshalText() ([]byte, error) {
	return []byte(e), nil
}

func (e *CommitOperation) UnmarshalText(text []byte) error {
	return e.Scan(text)
}

func (e CommitOperation) MarshalBinary() ([]byte, error) {
	return []byte(e), nil
}

func (e *CommitOperation) UnmarshalBinary(data []byte) error {
	return e.Scan(data)
}

func (e CommitOperation) Value() (driver.Value, error) {
	return string(e), nil
}

func (e *CommitOperation) Scan(value any) error {
	switch x := value.(type) {
	case string:
		*e = CommitOperation(x)
	case []byte:
		*e = CommitOperation(x)
	case nil:
		return fmt.Errorf("cannot nil into CommitOperation")
	default:
		return fmt.Errorf("cannot scan type %T: %v", value, value)
	}

	if !e.Valid() {
		return fmt.Errorf("invalid CommitOperation value: %s", *e)
	}

	return nil
}

// Enum values for EventKind
const (
	EventKindCommit   EventKind = "commit"
	EventKindAccount  EventKind = "account"
	EventKindIdentity EventKind = "identity"
)

func AllEventKind() []EventKind {
	return []EventKind{
		EventKindCommit,
		EventKindAccount,
		EventKindIdentity,
	}
}

type EventKind string

func (e EventKind) String() string {
	return string(e)
}

func (e EventKind) Valid() bool {
	switch e {
	case EventKindCommit,
		EventKindAccount,
		EventKindIdentity:
		return true
	default:
		return false
	}
}

// useful when testing in other packages
func (e EventKind) All() []EventKind {
	return AllEventKind()
}

func (e EventKind) MarshalText() ([]byte, error) {
	return []byte(e), nil
}

func (e *EventKind) UnmarshalText(text []byte) error {
	return e.Scan(text)
}

func (e EventKind) MarshalBinary() ([]byte, error) {
	return []byte(e), nil
}

func (e *EventKind) UnmarshalBinary(data []byte) error {
	return e.Scan(data)
}

func (e EventKind) Value() (driver.Value, error) {
	return string(e), nil
}

func (e *EventKind) Scan(value any) error {
	switch x := value.(type) {
	case string:
		*e = EventKind(x)
	case []byte:
		*e = EventKind(x)
	case nil:
		return fmt.Errorf("cannot nil into EventKind")
	default:
		return fmt.Errorf("cannot scan type %T: %v", value, value)
	}

	if !e.Valid() {
		return fmt.Errorf("invalid EventKind value: %s", *e)
	}

	return nil
}
