services:
  postgres:
    image: postgres:17

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: skylytics
      POSTGRES_DB: skylytics
      POSTGRES_PASSWORD: skylytics

    volumes:
      - postgresql:/var/lib/postgresql/data

  nats:
    image: nats
    command: ["-js"]
    ports:
      - "4222:4222"

volumes:
  postgresql:
    driver: local
