services:
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  nats:
    image: nats
    command: ["-js"]
    ports:
      - "4222:4222"

volumes:
  mongodb:
    driver: local
