version: '3'
env:
  POSTGRES_HOST: localhost
  POSTGRES_USER: skylytics
  POSTGRES_DB: skylytics
  POSTGRES_PASSWORD: skylytics
  PSQL_DSN:
    sh: echo "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable"
  DATABASE_URL:
    sh: echo $PSQL_DSN

tasks:
  default:
    desc: Run tests and linting
    cmds:
      - task: fmt-jsonnet
      - task: generate
      - task: lint-fix
      - task: test

  generate:
    cmds:
      - go generate ./...

  check:
    deps:
      - lint
      - test

  test:
    desc: Run tests
    cmds:
      - go test -race ./...

  cover:
    desc: Run tests with cover report
    cmds:
      - mkdir -p coverage/
      - go test -coverpkg=./... -coverprofile=coverage/cover.out ./...
      - go tool cover -html coverage/cover.out -o coverage/cover.html

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  lint-fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix

  fmt-jsonnet:
    vars:
      files:
        sh: "find . -type f \\( -name '*.jsonnet' -o -name '*.libsonnet' \\)"


    desc: 'Formats all libsonnet and jsonnet files'
    cmds:
        - |
          {{ range splitLines .files }}
            jsonnetfmt {{ . }} -o {{ . }}
          {{ end }}

  "db:migrate":
    cmd: dbmate migrate

  "db:rollback":
    cmd: dbmate rollback

  "run:subscriber":
    cmd: go run ./cmd/skylytics subscriber

