// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
	enums "skylytics/db/enums"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Event runs hooks after queries
var _ bob.HookableType = &Event{}

// Make sure the type SchemaMigration runs hooks after queries
var _ bob.HookableType = &SchemaMigration{}

// Make sure the type enums.EventKind satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.EventKind)(nil)

// Make sure the type enums.EventKind satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.EventKind)

// Make sure the type enums.CommitOperation satisfies database/sql.Scanner
var _ sql.Scanner = (*enums.CommitOperation)(nil)

// Make sure the type enums.CommitOperation satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(enums.CommitOperation)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])
