// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
	enums "skylytics/db/enums"
)

// Event is an object representing the database table.
type Event struct {
	Did            string                                `db:"did,pk" `
	TimeUs         time.Time                             `db:"time_us,pk" `
	Kind           enums.EventKind                       `db:"kind" `
	Rev            null.Val[string]                      `db:"rev" `
	Operation      null.Val[enums.CommitOperation]       `db:"operation" `
	Collection     null.Val[string]                      `db:"collection" `
	Rkey           null.Val[string]                      `db:"rkey" `
	Record         null.Val[types.JSON[json.RawMessage]] `db:"record" `
	Cid            null.Val[string]                      `db:"cid" `
	AccountActive  null.Val[bool]                        `db:"account_active" `
	AccountDid     null.Val[string]                      `db:"account_did" `
	AccountSeq     null.Val[int64]                       `db:"account_seq" `
	AccountStatus  null.Val[string]                      `db:"account_status" `
	AccountTime    null.Val[time.Time]                   `db:"account_time" `
	IdentityDid    null.Val[string]                      `db:"identity_did" `
	IdentityHandle null.Val[string]                      `db:"identity_handle" `
	IdentitySeq    null.Val[int64]                       `db:"identity_seq" `
	IdentityTime   null.Val[time.Time]                   `db:"identity_time" `
}

// EventSlice is an alias for a slice of pointers to Event.
// This should almost always be used instead of []*Event.
type EventSlice []*Event

// Events contains methods to work with the events table
var Events = psql.NewTablex[*Event, EventSlice, *EventSetter]("", "events", buildEventColumns("events"))

// EventsQuery is a query on the events table
type EventsQuery = *psql.ViewQuery[*Event, EventSlice]

func buildEventColumns(alias string) eventColumns {
	return eventColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"did", "time_us", "kind", "rev", "operation", "collection", "rkey", "record", "cid", "account_active", "account_did", "account_seq", "account_status", "account_time", "identity_did", "identity_handle", "identity_seq", "identity_time",
		).WithParent("events"),
		tableAlias:     alias,
		Did:            psql.Quote(alias, "did"),
		TimeUs:         psql.Quote(alias, "time_us"),
		Kind:           psql.Quote(alias, "kind"),
		Rev:            psql.Quote(alias, "rev"),
		Operation:      psql.Quote(alias, "operation"),
		Collection:     psql.Quote(alias, "collection"),
		Rkey:           psql.Quote(alias, "rkey"),
		Record:         psql.Quote(alias, "record"),
		Cid:            psql.Quote(alias, "cid"),
		AccountActive:  psql.Quote(alias, "account_active"),
		AccountDid:     psql.Quote(alias, "account_did"),
		AccountSeq:     psql.Quote(alias, "account_seq"),
		AccountStatus:  psql.Quote(alias, "account_status"),
		AccountTime:    psql.Quote(alias, "account_time"),
		IdentityDid:    psql.Quote(alias, "identity_did"),
		IdentityHandle: psql.Quote(alias, "identity_handle"),
		IdentitySeq:    psql.Quote(alias, "identity_seq"),
		IdentityTime:   psql.Quote(alias, "identity_time"),
	}
}

type eventColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	Did            psql.Expression
	TimeUs         psql.Expression
	Kind           psql.Expression
	Rev            psql.Expression
	Operation      psql.Expression
	Collection     psql.Expression
	Rkey           psql.Expression
	Record         psql.Expression
	Cid            psql.Expression
	AccountActive  psql.Expression
	AccountDid     psql.Expression
	AccountSeq     psql.Expression
	AccountStatus  psql.Expression
	AccountTime    psql.Expression
	IdentityDid    psql.Expression
	IdentityHandle psql.Expression
	IdentitySeq    psql.Expression
	IdentityTime   psql.Expression
}

func (c eventColumns) Alias() string {
	return c.tableAlias
}

func (eventColumns) AliasedAs(alias string) eventColumns {
	return buildEventColumns(alias)
}

// EventSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type EventSetter struct {
	Did            omit.Val[string]                          `db:"did,pk" `
	TimeUs         omit.Val[time.Time]                       `db:"time_us,pk" `
	Kind           omit.Val[enums.EventKind]                 `db:"kind" `
	Rev            omitnull.Val[string]                      `db:"rev" `
	Operation      omitnull.Val[enums.CommitOperation]       `db:"operation" `
	Collection     omitnull.Val[string]                      `db:"collection" `
	Rkey           omitnull.Val[string]                      `db:"rkey" `
	Record         omitnull.Val[types.JSON[json.RawMessage]] `db:"record" `
	Cid            omitnull.Val[string]                      `db:"cid" `
	AccountActive  omitnull.Val[bool]                        `db:"account_active" `
	AccountDid     omitnull.Val[string]                      `db:"account_did" `
	AccountSeq     omitnull.Val[int64]                       `db:"account_seq" `
	AccountStatus  omitnull.Val[string]                      `db:"account_status" `
	AccountTime    omitnull.Val[time.Time]                   `db:"account_time" `
	IdentityDid    omitnull.Val[string]                      `db:"identity_did" `
	IdentityHandle omitnull.Val[string]                      `db:"identity_handle" `
	IdentitySeq    omitnull.Val[int64]                       `db:"identity_seq" `
	IdentityTime   omitnull.Val[time.Time]                   `db:"identity_time" `
}

func (s EventSetter) SetColumns() []string {
	vals := make([]string, 0, 18)
	if s.Did.IsValue() {
		vals = append(vals, "did")
	}
	if s.TimeUs.IsValue() {
		vals = append(vals, "time_us")
	}
	if s.Kind.IsValue() {
		vals = append(vals, "kind")
	}
	if !s.Rev.IsUnset() {
		vals = append(vals, "rev")
	}
	if !s.Operation.IsUnset() {
		vals = append(vals, "operation")
	}
	if !s.Collection.IsUnset() {
		vals = append(vals, "collection")
	}
	if !s.Rkey.IsUnset() {
		vals = append(vals, "rkey")
	}
	if !s.Record.IsUnset() {
		vals = append(vals, "record")
	}
	if !s.Cid.IsUnset() {
		vals = append(vals, "cid")
	}
	if !s.AccountActive.IsUnset() {
		vals = append(vals, "account_active")
	}
	if !s.AccountDid.IsUnset() {
		vals = append(vals, "account_did")
	}
	if !s.AccountSeq.IsUnset() {
		vals = append(vals, "account_seq")
	}
	if !s.AccountStatus.IsUnset() {
		vals = append(vals, "account_status")
	}
	if !s.AccountTime.IsUnset() {
		vals = append(vals, "account_time")
	}
	if !s.IdentityDid.IsUnset() {
		vals = append(vals, "identity_did")
	}
	if !s.IdentityHandle.IsUnset() {
		vals = append(vals, "identity_handle")
	}
	if !s.IdentitySeq.IsUnset() {
		vals = append(vals, "identity_seq")
	}
	if !s.IdentityTime.IsUnset() {
		vals = append(vals, "identity_time")
	}
	return vals
}

func (s EventSetter) Overwrite(t *Event) {
	if s.Did.IsValue() {
		t.Did = s.Did.MustGet()
	}
	if s.TimeUs.IsValue() {
		t.TimeUs = s.TimeUs.MustGet()
	}
	if s.Kind.IsValue() {
		t.Kind = s.Kind.MustGet()
	}
	if !s.Rev.IsUnset() {
		t.Rev = s.Rev.MustGetNull()
	}
	if !s.Operation.IsUnset() {
		t.Operation = s.Operation.MustGetNull()
	}
	if !s.Collection.IsUnset() {
		t.Collection = s.Collection.MustGetNull()
	}
	if !s.Rkey.IsUnset() {
		t.Rkey = s.Rkey.MustGetNull()
	}
	if !s.Record.IsUnset() {
		t.Record = s.Record.MustGetNull()
	}
	if !s.Cid.IsUnset() {
		t.Cid = s.Cid.MustGetNull()
	}
	if !s.AccountActive.IsUnset() {
		t.AccountActive = s.AccountActive.MustGetNull()
	}
	if !s.AccountDid.IsUnset() {
		t.AccountDid = s.AccountDid.MustGetNull()
	}
	if !s.AccountSeq.IsUnset() {
		t.AccountSeq = s.AccountSeq.MustGetNull()
	}
	if !s.AccountStatus.IsUnset() {
		t.AccountStatus = s.AccountStatus.MustGetNull()
	}
	if !s.AccountTime.IsUnset() {
		t.AccountTime = s.AccountTime.MustGetNull()
	}
	if !s.IdentityDid.IsUnset() {
		t.IdentityDid = s.IdentityDid.MustGetNull()
	}
	if !s.IdentityHandle.IsUnset() {
		t.IdentityHandle = s.IdentityHandle.MustGetNull()
	}
	if !s.IdentitySeq.IsUnset() {
		t.IdentitySeq = s.IdentitySeq.MustGetNull()
	}
	if !s.IdentityTime.IsUnset() {
		t.IdentityTime = s.IdentityTime.MustGetNull()
	}
}

func (s *EventSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Events.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 18)
		if s.Did.IsValue() {
			vals[0] = psql.Arg(s.Did.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.TimeUs.IsValue() {
			vals[1] = psql.Arg(s.TimeUs.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Kind.IsValue() {
			vals[2] = psql.Arg(s.Kind.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Rev.IsUnset() {
			vals[3] = psql.Arg(s.Rev.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Operation.IsUnset() {
			vals[4] = psql.Arg(s.Operation.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Collection.IsUnset() {
			vals[5] = psql.Arg(s.Collection.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.Rkey.IsUnset() {
			vals[6] = psql.Arg(s.Rkey.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.Record.IsUnset() {
			vals[7] = psql.Arg(s.Record.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.Cid.IsUnset() {
			vals[8] = psql.Arg(s.Cid.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.AccountActive.IsUnset() {
			vals[9] = psql.Arg(s.AccountActive.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.AccountDid.IsUnset() {
			vals[10] = psql.Arg(s.AccountDid.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if !s.AccountSeq.IsUnset() {
			vals[11] = psql.Arg(s.AccountSeq.MustGetNull())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if !s.AccountStatus.IsUnset() {
			vals[12] = psql.Arg(s.AccountStatus.MustGetNull())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if !s.AccountTime.IsUnset() {
			vals[13] = psql.Arg(s.AccountTime.MustGetNull())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if !s.IdentityDid.IsUnset() {
			vals[14] = psql.Arg(s.IdentityDid.MustGetNull())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if !s.IdentityHandle.IsUnset() {
			vals[15] = psql.Arg(s.IdentityHandle.MustGetNull())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		if !s.IdentitySeq.IsUnset() {
			vals[16] = psql.Arg(s.IdentitySeq.MustGetNull())
		} else {
			vals[16] = psql.Raw("DEFAULT")
		}

		if !s.IdentityTime.IsUnset() {
			vals[17] = psql.Arg(s.IdentityTime.MustGetNull())
		} else {
			vals[17] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s EventSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s EventSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 18)

	if s.Did.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "did")...),
			psql.Arg(s.Did),
		}})
	}

	if s.TimeUs.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "time_us")...),
			psql.Arg(s.TimeUs),
		}})
	}

	if s.Kind.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "kind")...),
			psql.Arg(s.Kind),
		}})
	}

	if !s.Rev.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rev")...),
			psql.Arg(s.Rev),
		}})
	}

	if !s.Operation.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "operation")...),
			psql.Arg(s.Operation),
		}})
	}

	if !s.Collection.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "collection")...),
			psql.Arg(s.Collection),
		}})
	}

	if !s.Rkey.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rkey")...),
			psql.Arg(s.Rkey),
		}})
	}

	if !s.Record.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "record")...),
			psql.Arg(s.Record),
		}})
	}

	if !s.Cid.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cid")...),
			psql.Arg(s.Cid),
		}})
	}

	if !s.AccountActive.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_active")...),
			psql.Arg(s.AccountActive),
		}})
	}

	if !s.AccountDid.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_did")...),
			psql.Arg(s.AccountDid),
		}})
	}

	if !s.AccountSeq.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_seq")...),
			psql.Arg(s.AccountSeq),
		}})
	}

	if !s.AccountStatus.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_status")...),
			psql.Arg(s.AccountStatus),
		}})
	}

	if !s.AccountTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_time")...),
			psql.Arg(s.AccountTime),
		}})
	}

	if !s.IdentityDid.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_did")...),
			psql.Arg(s.IdentityDid),
		}})
	}

	if !s.IdentityHandle.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_handle")...),
			psql.Arg(s.IdentityHandle),
		}})
	}

	if !s.IdentitySeq.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_seq")...),
			psql.Arg(s.IdentitySeq),
		}})
	}

	if !s.IdentityTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_time")...),
			psql.Arg(s.IdentityTime),
		}})
	}

	return exprs
}

// FindEvent retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindEvent(ctx context.Context, exec bob.Executor, DidPK string, TimeUsPK time.Time, cols ...string) (*Event, error) {
	if len(cols) == 0 {
		return Events.Query(
			sm.Where(Events.Columns.Did.EQ(psql.Arg(DidPK))),
			sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(TimeUsPK))),
		).One(ctx, exec)
	}

	return Events.Query(
		sm.Where(Events.Columns.Did.EQ(psql.Arg(DidPK))),
		sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(TimeUsPK))),
		sm.Columns(Events.Columns.Only(cols...)),
	).One(ctx, exec)
}

// EventExists checks the presence of a single record by primary key
func EventExists(ctx context.Context, exec bob.Executor, DidPK string, TimeUsPK time.Time) (bool, error) {
	return Events.Query(
		sm.Where(Events.Columns.Did.EQ(psql.Arg(DidPK))),
		sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(TimeUsPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Event is retrieved from the database
func (o *Event) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Events.AfterSelectHooks.RunHooks(ctx, exec, EventSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Events.AfterInsertHooks.RunHooks(ctx, exec, EventSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Events.AfterUpdateHooks.RunHooks(ctx, exec, EventSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Events.AfterDeleteHooks.RunHooks(ctx, exec, EventSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Event
func (o *Event) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.Did,
		o.TimeUs,
	)
}

func (o *Event) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("events", "did"), psql.Quote("events", "time_us")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Event
func (o *Event) Update(ctx context.Context, exec bob.Executor, s *EventSetter) error {
	v, err := Events.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Event record with an executor
func (o *Event) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Events.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Event using the executor
func (o *Event) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Events.Query(
		sm.Where(Events.Columns.Did.EQ(psql.Arg(o.Did))),
		sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(o.TimeUs))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after EventSlice is retrieved from the database
func (o EventSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Events.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Events.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Events.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Events.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o EventSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("events", "did"), psql.Quote("events", "time_us")).In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o EventSlice) copyMatchingRows(from ...*Event) {
	for i, old := range o {
		for _, new := range from {
			if new.Did != old.Did {
				continue
			}
			if new.TimeUs.Equal(old.TimeUs) {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o EventSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Events.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Event:
				o.copyMatchingRows(retrieved)
			case []*Event:
				o.copyMatchingRows(retrieved...)
			case EventSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Event or a slice of Event
				// then run the AfterUpdateHooks on the slice
				_, err = Events.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o EventSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Events.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Event:
				o.copyMatchingRows(retrieved)
			case []*Event:
				o.copyMatchingRows(retrieved...)
			case EventSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Event or a slice of Event
				// then run the AfterDeleteHooks on the slice
				_, err = Events.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o EventSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals EventSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Events.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o EventSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Events.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o EventSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Events.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
