// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"encoding/json"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
	enums "skylytics/db/enums"
)

// Event is an object representing the database table.
type Event struct {
	Did            string                                `db:"did,pk" `
	TimeUs         time.Time                             `db:"time_us,pk" `
	Kind           enums.EventKind                       `db:"kind" `
	Rev            sql.Null[string]                      `db:"rev" `
	Operation      sql.Null[enums.CommitOperation]       `db:"operation" `
	Collection     sql.Null[string]                      `db:"collection" `
	Rkey           sql.Null[string]                      `db:"rkey" `
	Record         sql.Null[types.JSON[json.RawMessage]] `db:"record" `
	Cid            sql.Null[string]                      `db:"cid" `
	AccountActive  sql.Null[bool]                        `db:"account_active" `
	AccountDid     sql.Null[string]                      `db:"account_did" `
	AccountSeq     sql.Null[int64]                       `db:"account_seq" `
	AccountStatus  sql.Null[string]                      `db:"account_status" `
	AccountTime    sql.Null[time.Time]                   `db:"account_time" `
	IdentityDid    sql.Null[string]                      `db:"identity_did" `
	IdentityHandle sql.Null[string]                      `db:"identity_handle" `
	IdentitySeq    sql.Null[int64]                       `db:"identity_seq" `
	IdentityTime   sql.Null[time.Time]                   `db:"identity_time" `
}

// EventSlice is an alias for a slice of pointers to Event.
// This should almost always be used instead of []*Event.
type EventSlice []*Event

// Events contains methods to work with the events table
var Events = psql.NewTablex[*Event, EventSlice, *EventSetter]("", "events", buildEventColumns("events"))

// EventsQuery is a query on the events table
type EventsQuery = *psql.ViewQuery[*Event, EventSlice]

func buildEventColumns(alias string) eventColumns {
	return eventColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"did", "time_us", "kind", "rev", "operation", "collection", "rkey", "record", "cid", "account_active", "account_did", "account_seq", "account_status", "account_time", "identity_did", "identity_handle", "identity_seq", "identity_time",
		).WithParent("events"),
		tableAlias:     alias,
		Did:            psql.Quote(alias, "did"),
		TimeUs:         psql.Quote(alias, "time_us"),
		Kind:           psql.Quote(alias, "kind"),
		Rev:            psql.Quote(alias, "rev"),
		Operation:      psql.Quote(alias, "operation"),
		Collection:     psql.Quote(alias, "collection"),
		Rkey:           psql.Quote(alias, "rkey"),
		Record:         psql.Quote(alias, "record"),
		Cid:            psql.Quote(alias, "cid"),
		AccountActive:  psql.Quote(alias, "account_active"),
		AccountDid:     psql.Quote(alias, "account_did"),
		AccountSeq:     psql.Quote(alias, "account_seq"),
		AccountStatus:  psql.Quote(alias, "account_status"),
		AccountTime:    psql.Quote(alias, "account_time"),
		IdentityDid:    psql.Quote(alias, "identity_did"),
		IdentityHandle: psql.Quote(alias, "identity_handle"),
		IdentitySeq:    psql.Quote(alias, "identity_seq"),
		IdentityTime:   psql.Quote(alias, "identity_time"),
	}
}

type eventColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	Did            psql.Expression
	TimeUs         psql.Expression
	Kind           psql.Expression
	Rev            psql.Expression
	Operation      psql.Expression
	Collection     psql.Expression
	Rkey           psql.Expression
	Record         psql.Expression
	Cid            psql.Expression
	AccountActive  psql.Expression
	AccountDid     psql.Expression
	AccountSeq     psql.Expression
	AccountStatus  psql.Expression
	AccountTime    psql.Expression
	IdentityDid    psql.Expression
	IdentityHandle psql.Expression
	IdentitySeq    psql.Expression
	IdentityTime   psql.Expression
}

func (c eventColumns) Alias() string {
	return c.tableAlias
}

func (eventColumns) AliasedAs(alias string) eventColumns {
	return buildEventColumns(alias)
}

// EventSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type EventSetter struct {
	Did            *string                                `db:"did,pk" `
	TimeUs         *time.Time                             `db:"time_us,pk" `
	Kind           *enums.EventKind                       `db:"kind" `
	Rev            *sql.Null[string]                      `db:"rev" `
	Operation      *sql.Null[enums.CommitOperation]       `db:"operation" `
	Collection     *sql.Null[string]                      `db:"collection" `
	Rkey           *sql.Null[string]                      `db:"rkey" `
	Record         *sql.Null[types.JSON[json.RawMessage]] `db:"record" `
	Cid            *sql.Null[string]                      `db:"cid" `
	AccountActive  *sql.Null[bool]                        `db:"account_active" `
	AccountDid     *sql.Null[string]                      `db:"account_did" `
	AccountSeq     *sql.Null[int64]                       `db:"account_seq" `
	AccountStatus  *sql.Null[string]                      `db:"account_status" `
	AccountTime    *sql.Null[time.Time]                   `db:"account_time" `
	IdentityDid    *sql.Null[string]                      `db:"identity_did" `
	IdentityHandle *sql.Null[string]                      `db:"identity_handle" `
	IdentitySeq    *sql.Null[int64]                       `db:"identity_seq" `
	IdentityTime   *sql.Null[time.Time]                   `db:"identity_time" `
}

func (s EventSetter) SetColumns() []string {
	vals := make([]string, 0, 18)
	if s.Did != nil {
		vals = append(vals, "did")
	}
	if s.TimeUs != nil {
		vals = append(vals, "time_us")
	}
	if s.Kind != nil {
		vals = append(vals, "kind")
	}
	if s.Rev != nil {
		vals = append(vals, "rev")
	}
	if s.Operation != nil {
		vals = append(vals, "operation")
	}
	if s.Collection != nil {
		vals = append(vals, "collection")
	}
	if s.Rkey != nil {
		vals = append(vals, "rkey")
	}
	if s.Record != nil {
		vals = append(vals, "record")
	}
	if s.Cid != nil {
		vals = append(vals, "cid")
	}
	if s.AccountActive != nil {
		vals = append(vals, "account_active")
	}
	if s.AccountDid != nil {
		vals = append(vals, "account_did")
	}
	if s.AccountSeq != nil {
		vals = append(vals, "account_seq")
	}
	if s.AccountStatus != nil {
		vals = append(vals, "account_status")
	}
	if s.AccountTime != nil {
		vals = append(vals, "account_time")
	}
	if s.IdentityDid != nil {
		vals = append(vals, "identity_did")
	}
	if s.IdentityHandle != nil {
		vals = append(vals, "identity_handle")
	}
	if s.IdentitySeq != nil {
		vals = append(vals, "identity_seq")
	}
	if s.IdentityTime != nil {
		vals = append(vals, "identity_time")
	}
	return vals
}

func (s EventSetter) Overwrite(t *Event) {
	if s.Did != nil {
		t.Did = func() string {
			if s.Did == nil {
				return *new(string)
			}
			return *s.Did
		}()
	}
	if s.TimeUs != nil {
		t.TimeUs = func() time.Time {
			if s.TimeUs == nil {
				return *new(time.Time)
			}
			return *s.TimeUs
		}()
	}
	if s.Kind != nil {
		t.Kind = func() enums.EventKind {
			if s.Kind == nil {
				return *new(enums.EventKind)
			}
			return *s.Kind
		}()
	}
	if s.Rev != nil {
		t.Rev = func() sql.Null[string] {
			if s.Rev == nil {
				return *new(sql.Null[string])
			}
			v := s.Rev
			return *v
		}()
	}
	if s.Operation != nil {
		t.Operation = func() sql.Null[enums.CommitOperation] {
			if s.Operation == nil {
				return *new(sql.Null[enums.CommitOperation])
			}
			v := s.Operation
			return *v
		}()
	}
	if s.Collection != nil {
		t.Collection = func() sql.Null[string] {
			if s.Collection == nil {
				return *new(sql.Null[string])
			}
			v := s.Collection
			return *v
		}()
	}
	if s.Rkey != nil {
		t.Rkey = func() sql.Null[string] {
			if s.Rkey == nil {
				return *new(sql.Null[string])
			}
			v := s.Rkey
			return *v
		}()
	}
	if s.Record != nil {
		t.Record = func() sql.Null[types.JSON[json.RawMessage]] {
			if s.Record == nil {
				return *new(sql.Null[types.JSON[json.RawMessage]])
			}
			v := s.Record
			return *v
		}()
	}
	if s.Cid != nil {
		t.Cid = func() sql.Null[string] {
			if s.Cid == nil {
				return *new(sql.Null[string])
			}
			v := s.Cid
			return *v
		}()
	}
	if s.AccountActive != nil {
		t.AccountActive = func() sql.Null[bool] {
			if s.AccountActive == nil {
				return *new(sql.Null[bool])
			}
			v := s.AccountActive
			return *v
		}()
	}
	if s.AccountDid != nil {
		t.AccountDid = func() sql.Null[string] {
			if s.AccountDid == nil {
				return *new(sql.Null[string])
			}
			v := s.AccountDid
			return *v
		}()
	}
	if s.AccountSeq != nil {
		t.AccountSeq = func() sql.Null[int64] {
			if s.AccountSeq == nil {
				return *new(sql.Null[int64])
			}
			v := s.AccountSeq
			return *v
		}()
	}
	if s.AccountStatus != nil {
		t.AccountStatus = func() sql.Null[string] {
			if s.AccountStatus == nil {
				return *new(sql.Null[string])
			}
			v := s.AccountStatus
			return *v
		}()
	}
	if s.AccountTime != nil {
		t.AccountTime = func() sql.Null[time.Time] {
			if s.AccountTime == nil {
				return *new(sql.Null[time.Time])
			}
			v := s.AccountTime
			return *v
		}()
	}
	if s.IdentityDid != nil {
		t.IdentityDid = func() sql.Null[string] {
			if s.IdentityDid == nil {
				return *new(sql.Null[string])
			}
			v := s.IdentityDid
			return *v
		}()
	}
	if s.IdentityHandle != nil {
		t.IdentityHandle = func() sql.Null[string] {
			if s.IdentityHandle == nil {
				return *new(sql.Null[string])
			}
			v := s.IdentityHandle
			return *v
		}()
	}
	if s.IdentitySeq != nil {
		t.IdentitySeq = func() sql.Null[int64] {
			if s.IdentitySeq == nil {
				return *new(sql.Null[int64])
			}
			v := s.IdentitySeq
			return *v
		}()
	}
	if s.IdentityTime != nil {
		t.IdentityTime = func() sql.Null[time.Time] {
			if s.IdentityTime == nil {
				return *new(sql.Null[time.Time])
			}
			v := s.IdentityTime
			return *v
		}()
	}
}

func (s *EventSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Events.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 18)
		if s.Did != nil {
			vals[0] = psql.Arg(func() string {
				if s.Did == nil {
					return *new(string)
				}
				return *s.Did
			}())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.TimeUs != nil {
			vals[1] = psql.Arg(func() time.Time {
				if s.TimeUs == nil {
					return *new(time.Time)
				}
				return *s.TimeUs
			}())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Kind != nil {
			vals[2] = psql.Arg(func() enums.EventKind {
				if s.Kind == nil {
					return *new(enums.EventKind)
				}
				return *s.Kind
			}())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Rev != nil {
			vals[3] = psql.Arg(func() sql.Null[string] {
				if s.Rev == nil {
					return *new(sql.Null[string])
				}
				v := s.Rev
				return *v
			}())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Operation != nil {
			vals[4] = psql.Arg(func() sql.Null[enums.CommitOperation] {
				if s.Operation == nil {
					return *new(sql.Null[enums.CommitOperation])
				}
				v := s.Operation
				return *v
			}())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Collection != nil {
			vals[5] = psql.Arg(func() sql.Null[string] {
				if s.Collection == nil {
					return *new(sql.Null[string])
				}
				v := s.Collection
				return *v
			}())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Rkey != nil {
			vals[6] = psql.Arg(func() sql.Null[string] {
				if s.Rkey == nil {
					return *new(sql.Null[string])
				}
				v := s.Rkey
				return *v
			}())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.Record != nil {
			vals[7] = psql.Arg(func() sql.Null[types.JSON[json.RawMessage]] {
				if s.Record == nil {
					return *new(sql.Null[types.JSON[json.RawMessage]])
				}
				v := s.Record
				return *v
			}())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.Cid != nil {
			vals[8] = psql.Arg(func() sql.Null[string] {
				if s.Cid == nil {
					return *new(sql.Null[string])
				}
				v := s.Cid
				return *v
			}())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.AccountActive != nil {
			vals[9] = psql.Arg(func() sql.Null[bool] {
				if s.AccountActive == nil {
					return *new(sql.Null[bool])
				}
				v := s.AccountActive
				return *v
			}())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.AccountDid != nil {
			vals[10] = psql.Arg(func() sql.Null[string] {
				if s.AccountDid == nil {
					return *new(sql.Null[string])
				}
				v := s.AccountDid
				return *v
			}())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.AccountSeq != nil {
			vals[11] = psql.Arg(func() sql.Null[int64] {
				if s.AccountSeq == nil {
					return *new(sql.Null[int64])
				}
				v := s.AccountSeq
				return *v
			}())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if s.AccountStatus != nil {
			vals[12] = psql.Arg(func() sql.Null[string] {
				if s.AccountStatus == nil {
					return *new(sql.Null[string])
				}
				v := s.AccountStatus
				return *v
			}())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if s.AccountTime != nil {
			vals[13] = psql.Arg(func() sql.Null[time.Time] {
				if s.AccountTime == nil {
					return *new(sql.Null[time.Time])
				}
				v := s.AccountTime
				return *v
			}())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if s.IdentityDid != nil {
			vals[14] = psql.Arg(func() sql.Null[string] {
				if s.IdentityDid == nil {
					return *new(sql.Null[string])
				}
				v := s.IdentityDid
				return *v
			}())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if s.IdentityHandle != nil {
			vals[15] = psql.Arg(func() sql.Null[string] {
				if s.IdentityHandle == nil {
					return *new(sql.Null[string])
				}
				v := s.IdentityHandle
				return *v
			}())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		if s.IdentitySeq != nil {
			vals[16] = psql.Arg(func() sql.Null[int64] {
				if s.IdentitySeq == nil {
					return *new(sql.Null[int64])
				}
				v := s.IdentitySeq
				return *v
			}())
		} else {
			vals[16] = psql.Raw("DEFAULT")
		}

		if s.IdentityTime != nil {
			vals[17] = psql.Arg(func() sql.Null[time.Time] {
				if s.IdentityTime == nil {
					return *new(sql.Null[time.Time])
				}
				v := s.IdentityTime
				return *v
			}())
		} else {
			vals[17] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s EventSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s EventSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 18)

	if s.Did != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "did")...),
			psql.Arg(s.Did),
		}})
	}

	if s.TimeUs != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "time_us")...),
			psql.Arg(s.TimeUs),
		}})
	}

	if s.Kind != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "kind")...),
			psql.Arg(s.Kind),
		}})
	}

	if s.Rev != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rev")...),
			psql.Arg(s.Rev),
		}})
	}

	if s.Operation != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "operation")...),
			psql.Arg(s.Operation),
		}})
	}

	if s.Collection != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "collection")...),
			psql.Arg(s.Collection),
		}})
	}

	if s.Rkey != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rkey")...),
			psql.Arg(s.Rkey),
		}})
	}

	if s.Record != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "record")...),
			psql.Arg(s.Record),
		}})
	}

	if s.Cid != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cid")...),
			psql.Arg(s.Cid),
		}})
	}

	if s.AccountActive != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_active")...),
			psql.Arg(s.AccountActive),
		}})
	}

	if s.AccountDid != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_did")...),
			psql.Arg(s.AccountDid),
		}})
	}

	if s.AccountSeq != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_seq")...),
			psql.Arg(s.AccountSeq),
		}})
	}

	if s.AccountStatus != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_status")...),
			psql.Arg(s.AccountStatus),
		}})
	}

	if s.AccountTime != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_time")...),
			psql.Arg(s.AccountTime),
		}})
	}

	if s.IdentityDid != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_did")...),
			psql.Arg(s.IdentityDid),
		}})
	}

	if s.IdentityHandle != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_handle")...),
			psql.Arg(s.IdentityHandle),
		}})
	}

	if s.IdentitySeq != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_seq")...),
			psql.Arg(s.IdentitySeq),
		}})
	}

	if s.IdentityTime != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "identity_time")...),
			psql.Arg(s.IdentityTime),
		}})
	}

	return exprs
}

// FindEvent retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindEvent(ctx context.Context, exec bob.Executor, DidPK string, TimeUsPK time.Time, cols ...string) (*Event, error) {
	if len(cols) == 0 {
		return Events.Query(
			sm.Where(Events.Columns.Did.EQ(psql.Arg(DidPK))),
			sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(TimeUsPK))),
		).One(ctx, exec)
	}

	return Events.Query(
		sm.Where(Events.Columns.Did.EQ(psql.Arg(DidPK))),
		sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(TimeUsPK))),
		sm.Columns(Events.Columns.Only(cols...)),
	).One(ctx, exec)
}

// EventExists checks the presence of a single record by primary key
func EventExists(ctx context.Context, exec bob.Executor, DidPK string, TimeUsPK time.Time) (bool, error) {
	return Events.Query(
		sm.Where(Events.Columns.Did.EQ(psql.Arg(DidPK))),
		sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(TimeUsPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Event is retrieved from the database
func (o *Event) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Events.AfterSelectHooks.RunHooks(ctx, exec, EventSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Events.AfterInsertHooks.RunHooks(ctx, exec, EventSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Events.AfterUpdateHooks.RunHooks(ctx, exec, EventSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Events.AfterDeleteHooks.RunHooks(ctx, exec, EventSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Event
func (o *Event) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.Did,
		o.TimeUs,
	)
}

func (o *Event) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("events", "did"), psql.Quote("events", "time_us")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Event
func (o *Event) Update(ctx context.Context, exec bob.Executor, s *EventSetter) error {
	v, err := Events.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Event record with an executor
func (o *Event) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Events.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Event using the executor
func (o *Event) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Events.Query(
		sm.Where(Events.Columns.Did.EQ(psql.Arg(o.Did))),
		sm.Where(Events.Columns.TimeUs.EQ(psql.Arg(o.TimeUs))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after EventSlice is retrieved from the database
func (o EventSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Events.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Events.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Events.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Events.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o EventSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("events", "did"), psql.Quote("events", "time_us")).In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o EventSlice) copyMatchingRows(from ...*Event) {
	for i, old := range o {
		for _, new := range from {
			if new.Did != old.Did {
				continue
			}
			if new.TimeUs.Equal(old.TimeUs) {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o EventSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Events.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Event:
				o.copyMatchingRows(retrieved)
			case []*Event:
				o.copyMatchingRows(retrieved...)
			case EventSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Event or a slice of Event
				// then run the AfterUpdateHooks on the slice
				_, err = Events.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o EventSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Events.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Event:
				o.copyMatchingRows(retrieved)
			case []*Event:
				o.copyMatchingRows(retrieved...)
			case EventSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Event or a slice of Event
				// then run the AfterDeleteHooks on the slice
				_, err = Events.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o EventSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals EventSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Events.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o EventSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Events.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o EventSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Events.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
