name: Test, lint, build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run tests
        run: go test -race ./...

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: ko-build/setup-ko@v0.6

      - name: Build and push image with ko
        env:
          KO_DOCKER_REPO: ghcr.io/zhulik
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ko build -B --tags latest skylytics/cmd/skylytics
